name: Docs Export
on:
  [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    
    - name: Install Emacs
      run: nix profile install nixpkgs#emacs29

    - name: Configure Git
      run: |
        git config user.name 'github-actions'
        git config user.email 'actions@github.com'

    - name: Export docs
      run: |
        chmod 0755 ./bin/org-export-to
        ./bin/org-export-to ./docs/deck52.org README
        cp -f ./docs/README.org ./README.org
        git commit -m "docs(README): update" README.org || :

    - name: Push Updates
      run: |
        git pull --rebase --autostash
        git push
